config/routes.rb
JobOrder001::Application.routes.draw do

  resources :jobs do
    put :mark_as_done, :on => :member
    get :accomplished, :on => :collection
  end

  devise_for :users

  put "/accomplished/:id" => "pages#accomplished", :as => "accomplished"
  
  match '/sales', 	:to => 'pages#sales'
  match '/delivery',    :to => 'pages#delivery'
  match '/joborder',    :to => 'pages#joborder'
  match '/training',    :to => 'pages#training'
  match '/collection',    :to => 'pages#collection'
  root :to => "pages#joborder"

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!, # :except => [:index, :accomplished ]
  
  
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.xml
  def index
    @jobs = Job.where(:done => nil)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @jobs }
    end
  end
 
  # GET /jobs/1
  # GET /jobs/1.xml
  def show
    @job = Job.find(params[:id])
   
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.xml
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.xml
  def create
    @job = Job.new(params[:job])
    
    respond_to do |format|
      if @job.save 
        format.html { redirect_to(@job, :notice => 'Job was successfully created.') }
        format.xml  { render :xml => @job, :status => :created, :location => @job }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @job.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.xml
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to(@job, :notice => 'Job was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @job.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.xml
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to(jobs_url) }
      format.xml  { head :ok }
    end
  end


  # put /jobs/1/mark_as_done
  def mark_as_done
    job = Job.find params[:id]
    job.update_attributes(:done => true)
    redirect_to accomplished_jobs_path
  end

  # get /jobs/accomplished
  def accomplished
    @jobs = Job.where(:done => true)
    render :template => "jobs/index"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def accomplished
    @job = Job.find params[:id]
    @job.update_attributes(:done => true)
    redirect_to accomplished_path(job)
  end 
  
  def current_user
  end

  def sales
  end
  
  def delivery
  end
  
  def joborder
  end
 
  def training
  end
  
  def collection
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
 
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  
end

app/views/jobs/_form.html.erb
<div class="email">
<%= current_user.email if user_signed_in? %>
</div>


<div class="status hidden">
<%= semantic_form_for(@job) do |f| %>
  <%= f.inputs do %>
  <%= f.label :date_time_started %><br />
  <%= f.datetime_select :date_time_started, :as => DateTime.now.strftime("%M %d, %Y") %>
					 

  <%= f.input :id,                       :start_year    => 2011,
                                         :label => "Auto Generate" %>


  <%= f.input :status,                   :include_blank => false, 
                                         :collection => [["-Ongoing -"," Ongoing "]],
					 :hint => ""%>



  <%= f.input :prepared_by,              :include_blank => false, 
                                         :collection => [["- Auto Generated -","  ",current_user.email]],
					 :hint => ""%>
  </div>

  

<table width="750" border="1" align="center">
   <tr>
      <th width="114" scope="col">&nbsp;</th>
      <th width="247" scope="col">&nbsp;</th>
      <th width="114" scope="col">&nbsp;</th>
      <th width="247" scope="col">&nbsp;</th>
   </tr>
   <tr>
  
      <td>Company Name </td>
      <td><%= f.input :company, :label => ":"%></td>
      <td>Category / System </td>
      <td><%= f.input :system_model,    :include_blank => false, 
					:collection => [["- Select -"," Blank "],
							["Automatic Gates"," Automatic Gates"],
 					 	        ["Metal Detectors","Metal Detectors"],
							["CCTV","CCTV"],
							["Access Control","Access Control"],
							["Intrusion","Intrusion"],
							["Fire Alarm","Fire Alarm"],
							["Light Automation","Light Automation"],
							["Automated Window Treatment","Automated Window Treatment"],
							["Home Run","Home Run"],
							["Installation Accessories","Installation Accessories"],
							["Cable","Cable"],
 							["Radio","Radio"],
							["Voip","Voip"],
							["Network Cabinet","Network Cabinet"],
							["Public Address System","Public Address System"],
							["Telecom","Telecom"],
							["Id Printer","Id Printer"],
							["Pc Pheripherals","Pc Pheripherals"],
							["Card","Card"],
							["Networking","Networking"],
							["Door Automation","Door Automation"],
							["Parking System","Parking System"],
							["Turnstile","Turnstile"],
							["Blank","Blank"],
							["Others","Others"],
							["Others","Others"]],
				 			:label => ":"%></td>
   </tr>
   <tr>
      <td>Contact Person </td>
      <td><%= f.input :contact_person, :label => ":"%></td>
      <td>Technical </td>
      <td><%= f.input :technical, :label => ":" %></td>
   </tr>
   <tr>
      <td>Address  </td>
      <td><%= f.input :address, :label => ":"%></td>
      <td>Status</td>
      <td><%= f.input :status, :collection => [["- ONGOING -"," ONGOING "],[" FINISHED "," FINISHED "]], 
	                       :include_blank => false,  
                               :label => "." %></td>
      </tr>
   <tr>
      <td>Contact Number </td>
      <td><%= f.input :contact_no, :label => ":"%></td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
   </tr>
</table>
   <table width="750" border="1" align="center">
   <tr>
      <th width="89" scope="col">&nbsp;</th>
      <th width="667" scope="col">&nbsp;</th>
      </tr>
   <tr>
      <td>To Do:</td>
      <td height="90"><%= f.input :todo, :label => "."%></td>
   </tr>
   <tr>
      <td>Work Done:</td>
      <td height="90"><%= f.input :work_done, :label => "."%></td>
   </tr>
   <tr>
      <td>Remarks:</td>
      <td height="90"><%= f.input :remarks, :label => "."%></td>
   </tr>
   <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
   </tr>
</table>

<% end %>

<table width="100" border="1" align="center">
        <tr>
            <th scope="col"><div align="center"><%= f.buttons %></div></th>
        </tr>
</table>
<p>&nbsp;</p>

<% end %>

app/views/jobs/edit.html.erb
<div id="link">
  <%= link_to "Create JO ", new_job_path %> |
  <%= link_to 'Ongoing', jobs_path %> |
  <%= link_to "Finished ", accomplished_jobs_path %> |
  <%= link_to "Sign out",  destroy_user_session_path,  :method=> :delete %> 
  <b><%= current_user.email if user_signed_in? %></b>
</div>
<h1>Update Job Order</h1>

<div class="status hidden">
<%= semantic_form_for(@job) do |f| %>
  <%= f.inputs do %>
  <%= f.input :date_time_started,        :include_blank => false, 
  					 :collection => [["- Auto Generated -","  ",Time.now.in_time_zone("Eastern Time (US & Canada)")]],
					 :hint => "",
                                         :label => "Time/Date"%>
					 

  <%= f.input :id,                       :start_year    => 2011,
                                         :label => "Auto Generate" %>

 
  <%= f.input :status,                   :include_blank => false, 
                                         :collection => [["-Ongoing -"," Ongoing "]],
					 :hint => ""%>



  <%= f.input :prepared_by,              :include_blank => false, 
                                         :collection => [["- Auto Generated -","  ",current_user.email]],
					 :hint => ""%>
  </div>
 


<table width="750" border="1" align="center">
   <tr>
      <th width="114" scope="col">&nbsp;</th>
      <th width="247" scope="col">&nbsp;</th>
      <th width="114" scope="col">&nbsp;</th>
      <th width="247" scope="col">&nbsp;</th>
   </tr>
   
   <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
   </tr>
   <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>Technical </td>
      <td><%= f.input :technical, :label => ":" %></td>
   </tr>
   <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>Status</td>
      <td><%= f.input :status, :collection => [["-Ongoing -"," Ongoing "],["Finished","Finished"]], 
	                       :include_blank => false,  
                               :label => "." %></td>
      </tr>
   <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
   </tr>
</table>
   <table width="750" border="1" align="center">
   <tr>
      <th width="89" scope="col">&nbsp;</th>
      <th width="667" scope="col">&nbsp;</th>
      </tr>
   <tr>
      <td>To Do:</td>
      <td height="90"><%= f.input :todo, :label => "."%></td>
   </tr>
   <tr>
      <td>Work Done:</td>
      <td height="90"><%= f.input :work_done, :label => "."%></td>
   </tr>
   <tr>
      <td>Remarks:</td>
      <td height="90"><%= f.input :remarks, :label => "."%></td>
   </tr>
   <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
   </tr>
</table>

<% end %>

<table width="100" border="1" align="center">
     <div class="status hidden">

        <tr>
            <th scope="col"><div align="center"><%= f.buttons %></div></th>
        </tr>
</table>
<p>&nbsp;</p>

<% end %>

app/views/jobs/index.html.erb
<div id="link">
  
  <%= link_to "Create JO ", new_job_path %> |
  <%= link_to 'Ongoing', jobs_path %> |
  <%= link_to "Finished ", accomplished_jobs_path %> |
  <%= link_to "Sign out",  destroy_user_session_path,  :method=> :delete %>

</div>
<h1>Job Order</h1>
<div class="email">
<%= current_user.email if user_signed_in? %>
</div>
<table>
  <tr>
    <th>Created Date:</th>
    <th>Ref No:</th>
    <th>Company</th>
    <th>Technical</th>
    <th>Prepared by</th>
    <th>Status</th>
    <th></th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.date_time_started %></td>
    <td><%= link_to job.id, job_path(job) %></td>
    <td><%= job.company %></td>
    <td><%= job.technical %></td>
    <td><%= job.prepared_by %></td>
    <td><%= job.status %></td>
    <td><%= link_to 'Update', edit_job_path(job) %></td>
    <td><%= link_to "Done", mark_as_done_job_path(job),:confirm => 'ARE YOU SURE THAT THIS IS FINISHED??', :method => :put %><td>
    <!-- <td><%= link_to 'Trash', job, :confirm => 'Are you sure?', :method => :delete %>-->
  </tr>
<% end %>
</table>
 

<br />

app/views/jobs/new.html.erb
<div id="link">
  <%= link_to "Create JO ", new_job_path %> |
  <%= link_to 'Ongoing', jobs_path %> |
  <%= link_to "Finished ", accomplished_jobs_path %> |
  <%= link_to "Sign out",  destroy_user_session_path,  :method=> :delete %> 
</div>
<h4>Enter New job Order</h4>


<%= render 'form' %>

app/views/jobs/show.html.erb
<style type="text/css">
   @media print{
   
   #link{ display:none;}
   
   }
</style>

<div id="link">
	<%= link_to "Create JO ", new_job_path %> |
	<%= link_to 'Ongoing', jobs_path %> |
	<%= link_to "Finished ", accomplished_jobs_path %> |
	<%= link_to "Sign out", destroy_user_session_path, :method=> :delete %>

</div>
  <header>
   <%= image_tag("header2.1.jpg", :alt => "ASI-HEADER", :class => "round") %>
  </headers>

<style type="text/css">
 h4 { color:olive;font-size: 16pt; }
 p { color: #5C5858;font-size: 14pt; }
 b { color:#000; font size="4" }
</style>

<div align="left">
    
    <table border="2" cellpadding="0" cellspacing="0" width="100%">
      <tr>
        <th width="55%"><h4><b>Generated Job-order NO:</b> 2011-0<%= @job.id %></h4></th>
        <th width="45%"></th>
      </tr>
      <tr>
        <td><p><b>Generated Date:</b><%= @job.date_time_started %></p></td>
        <td><p><b>Datetime Finished:</b><%= @job.date_time_finished %></p></td>
      </tr>
      <tr>
        <td><p><b>Company:</b><%= @job.company %></p></td>
        <td><p><b>Technical:</b><%= @job.technical %></p></td>
      </tr>
      <tr>
        <td><p><b>Address:</b><%= @job.address %></p></td>
        <td><p><b>Category / System:</b><%= @job.system_model %></p></td>
      </tr>
      <tr>
        <td><p><b>Contact Person:</b><%= @job.contact_person %></p></td>
        <td></td>
      </tr>
      <tr>
        <td><p><b>Contact No:</b><%= @job.contact_no %></p></td>
        <td></td>
      </tr>
    </table>
    <table border="2" cellpadding="10" cellspacing="10" width="100%"> 
      <tr>
        <td height="135"><p><b>To Do:</b><%= @job.todo %></p></td>
      </tr>
      <tr>
        <td height="135"><p><b>Work Done:</b><%= @job.work_done %></p></td>
      </tr>
      <tr>
        <td height="135"><p><b>Remarks:</b><%= @job.remarks %></p></td>
      </tr>
    </table>
    <table border="2" cellpadding="0" cellspacing="0" width="100%">
      <tr>
        <td width="55%"><p><b>Prepared by:</b><%= @job.prepared_by %></p></td>
        <td width="45%"><p><b>Approved by:</b>____________________</p></td>
      </tr>
      <tr>
        <td><p><b>Status:</b><%= @job.status %></p></td>
        <td><p><b>Client Signature:</b>____________________</p></td>
      </tr>

      </table>
</div>
  </span> 
   <input type=button onclick="window.print()" value='PRINT'>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<style type="text/css">
   @media print{
   
   
   #head{ display:none;}
   
   }
</style>
<div id="head">
<header>
       
        <nav class="round">
          <ul>
            <li><%= link_to "Sales Order", sales_path %></li>
            <li><%= link_to 'Delivery Receipt', delivery_path %></li>
            <li><%= link_to "Job Order ", jobs_path %></li>
            <li><%= link_to "Training", training_path %></li>
            <li><%= link_to "Collection", collection_path %></li>
          </ul>
        
        </nav>
</header>
</div>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ASI-MONITORING SYSTEM</title>
  <%= render 'layouts/stylesheets' %>
</head>
<body>
  <div class="container">
   
      <section class="round">
        <div class="signout">
          
          
          
        </div>
        
        <h5>v.4.0.2</h5>
        <%= yield %>
      </section>
  
    </div>

</body>
</html>

app/views/pages/accomplished.html.erb
<h1>Finished Job-Order</h1>
<p>Loading. . .</p>

app/views/pages/collection.html.erb
<div id="link">
  <%= link_to "Add CO ", '#' %> |
  <%= link_to 'Uncollect', '#' %> |
  <%= link_to "Recieved", '#' %> |
  <%= link_to "Sign out",  destroy_user_session_path,  :method=> :delete %> 

</div>
<h1>Collection</h1>

<p>Loading. . .</p>

app/views/pages/delivery.html.erb
<div id="link">
  <%= link_to "Add DR ", '#' %> |
  <%= link_to 'On Delivery', '#' %> |
  <%= link_to "Recieved ", '#' %> |
  <%= link_to "Sign out",  destroy_user_session_path,  :method=> :delete %> 

</div>
<h1>Delivery Receipt</h1>

<p>Loading. . .</p>

app/views/pages/joborder.html.erb
<div id="link">
  <%= link_to "Create JO ", new_job_path %> |
  <%= link_to 'Ongoing', jobs_path %> |
  <%= link_to "Finished ", accomplished_jobs_path %> |
  <%= link_to "Sign out",  destroy_user_session_path,  :method=> :delete %> 
</div>
<h1>Job Order</h1>

<p>Loading. . .</p>

app/views/pages/sales.html.erb
<div id="link">
  <%= link_to "Add SO ", '#' %> |
  <%= link_to 'Sales List', '#' %> |
  <%= link_to "Sales Close ", '#' %> |
  <%= link_to "Sign out",  destroy_user_session_path,  :method=> :delete %> 
</div>
<h1>Sales Order</h1>

<p>Loading. . .</p>

app/views/pages/training.html.erb
<div id="link">
  <%= link_to "Add TR ", '#' %> |
  <%= link_to 'Training Schedule', '#' %> |
  <%= link_to "Finished ", '#' %> |
  <%= link_to "Sign out",  destroy_user_session_path,  :method=> :delete %> 
</div>
<h1>Training Call</h1>
<p>Loading. . .</p>